apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crawler-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SiriusKoan/nycu-cloud-native-final-project.git
    targetRevision: HEAD
    path: applications/crawler

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

